// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBenhXa.Models;

#nullable disable

namespace QuanLyBenhXa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260115173051_AddDonThuocAndWorkflow")]
    partial class AddDonThuocAndWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyBenhXa.Models.BacSi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapBac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongKham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BacSis");
                });

            modelBuilder.Entity("QuanLyBenhXa.Models.BenhNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapBac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoBHYT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BenhNhans");
                });

            modelBuilder.Entity("QuanLyBenhXa.Models.DonThuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CachDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoSoKhamBenhId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("ThuocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoSoKhamBenhId");

                    b.HasIndex("ThuocId");

                    b.ToTable("DonThuocs");
                });

            modelBuilder.Entity("QuanLyBenhXa.Models.HoSoKhamBenh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BacSiPhuTrach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("int");

                    b.Property<string>("KetLuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongYeuCau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrieuChung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("HoSoKhamBenhs");
                });

            modelBuilder.Entity("QuanLyBenhXa.Models.KetQuaKhamBenh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BacSiThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoSoKhamBenhId")
                        .HasColumnType("int");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenPhongKham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoKhamBenhId");

                    b.ToTable("KetQuaKhamBenhs");
                });

            modelBuilder.Entity("QuanLyBenhXa.Models.Thuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhaSanXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongTonKho")
                        .HasColumnType("int");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Thuocs");
                });

            modelBuilder.Entity("QuanLyBenhXa.Models.DonThuoc", b =>
                {
                    b.HasOne("QuanLyBenhXa.Models.HoSoKhamBenh", "HoSoKhamBenh")
                        .WithMany("DonThuocs")
                        .HasForeignKey("HoSoKhamBenhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBenhXa.Models.Thuoc", "Thuoc")
                        .WithMany()
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoKhamBenh");

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("QuanLyBenhXa.Models.HoSoKhamBenh", b =>
                {
                    b.HasOne("QuanLyBenhXa.Models.BenhNhan", "BenhNhan")
                        .WithMany("HoSoKhamBenhs")
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("QuanLyBenhXa.Models.KetQuaKhamBenh", b =>
                {
                    b.HasOne("QuanLyBenhXa.Models.HoSoKhamBenh", "HoSoKhamBenh")
                        .WithMany("KetQuaKhamBenhs")
                        .HasForeignKey("HoSoKhamBenhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoKhamBenh");
                });

            modelBuilder.Entity("QuanLyBenhXa.Models.BenhNhan", b =>
                {
                    b.Navigation("HoSoKhamBenhs");
                });

            modelBuilder.Entity("QuanLyBenhXa.Models.HoSoKhamBenh", b =>
                {
                    b.Navigation("DonThuocs");

                    b.Navigation("KetQuaKhamBenhs");
                });
#pragma warning restore 612, 618
        }
    }
}
